apiVersion: batch/v1
kind: Job
metadata:
  name: listing
spec:
  template:
    metadata:
    spec:
      containers:
      - image: listing
        imagePullPolicy: IfNotPresent
        name: listing
      restartPolicy: Never
